baseURL: https://blog.cloud-guru.io/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Cloud-Guru, le Blog

languages:
    fr:
        languageName: Français
        title: Cloud-Guru, le Blog
        weight: 1
    # en:
    #     languageName: English
    #     title: Cloud-Guru Blog
    #     weight: 2

# GA Tracking ID
# googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: fr

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
# hasCJKLanguage: false

# permalinks:
#   post: /p/:slug/
#   page: /:slug/

params:
  mermaid:
    enable: true

  mainSections:
    - post
  # featuredImageField: image
  # rssFullContent: true
  # favicon:

  # sectionPagesMenu: home

  footer:
    since: 2022
    customText:

  dateFormat:
    published: January 02, 2006
    lastUpdated: January 02, 2006

  sidebar:
    compact: false
    emoji: 🇺🇦
    subtitle: "Guru (du sanskrit : गुरु) est un enseignant, précepteur ou maître."
    avatar:
      enabled: true
      local: true
      src: img/bad-toro-150.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: utterances

    utterances:
      repo: isibox/isibox.github.io 
      issueTerm: pathname
      label: Ceci est le label

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  colorScheme:
    # Display toggle
    toggle: true
    # Available values: auto, light, dark
    default: auto

markup:
  highlight:
    lineNos: false
    lineNumbersInTable: true
    style: native
    # style: solarized-dark256
    # style: vim

menu:
  main: []
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/isibox
      params:
        icon: brand-github